var I0;
(function (I0) {
    I0.ContextLabels = ["Product Line", "Sub-Domain", "Business Process", "Product", "Configuration"];
    I0.ContextPluralLabels = ["Product Lines", "Sub-Domains", "Business Processes", "Products", "Configurations"];
    I0.ContextItemLabels = ["Project", "Concept", "Use Case", "Version", "Comparison Matrix"];
    I0.RuleTypeOptions = new Array();
    I0.RuleTypeOptions.push(new I0.ItemViewModel("Definition", "1"));
    I0.RuleTypeOptions.push(new I0.ItemViewModel("Structure", "2"));
    I0.RuleTypeOptions.push(new I0.ItemViewModel("Decision", "3"));
    I0.RuleTypeOptions.push(new I0.ItemViewModel("Behavior", "4"));
    I0.RuleTypeExamples = new Array();
    I0.RuleTypeExamples.push(new I0.ItemViewModel("Ex: <term> MUST HAVE < at least, at most, exactly...> <term>", "1"));
    I0.RuleTypeExamples.push(new I0.ItemViewModel("Ex : <term> MUST BE IN LIST < a, b, c...>", "2"));
    I0.RuleTypeExamples.push(new I0.ItemViewModel("Ex : IF <condition> THEN <action>", "3"));
    I0.RuleTypeExamples.push(new I0.ItemViewModel("Ex : <actor> MUST DO or not DO <#UCX, #FeatureY, #FeatureZ...>", "4"));
    I0.DocumentationSteps = new Array();
    I0.DocumentationSteps.push(new I0.ItemViewModel("New", "1"));
    I0.DocumentationSteps.push(new I0.ItemViewModel("Draft", "2"));
    I0.DocumentationSteps.push(new I0.ItemViewModel("Reviewed", "3"));
    I0.DocumentationSteps.push(new I0.ItemViewModel("Approved", "4"));
    I0.UseCaseScopes = new Array();
    I0.UseCaseScopes.push(new I0.ItemViewModel("System (black-box)", "1"));
    I0.UseCaseScopes.push(new I0.ItemViewModel("System (white-box)", "2"));
    I0.UseCaseScopes.push(new I0.ItemViewModel("Component", "3"));
    I0.UseCaseLevels = new Array();
    I0.UseCaseLevels.push(new I0.ItemViewModel("User Goal", "1"));
    I0.UseCaseLevels.push(new I0.ItemViewModel("Infrastructure", "2"));
    I0.MonthOptions = new Array();
    I0.MonthOptions.push(new I0.ItemViewModel("January", "1"));
    I0.MonthOptions.push(new I0.ItemViewModel("February", "2"));
    I0.MonthOptions.push(new I0.ItemViewModel("March", "3"));
    I0.MonthOptions.push(new I0.ItemViewModel("April", "4"));
    I0.MonthOptions.push(new I0.ItemViewModel("May", "5"));
    I0.MonthOptions.push(new I0.ItemViewModel("June", "6"));
    I0.MonthOptions.push(new I0.ItemViewModel("July", "7"));
    I0.MonthOptions.push(new I0.ItemViewModel("August", "8"));
    I0.MonthOptions.push(new I0.ItemViewModel("September", "9"));
    I0.MonthOptions.push(new I0.ItemViewModel("October", "10"));
    I0.MonthOptions.push(new I0.ItemViewModel("November", "11"));
    I0.MonthOptions.push(new I0.ItemViewModel("December", "12"));
    I0.YearOptions = new Array();
    I0.YearOptions.push(new I0.ItemViewModel("2018", "2018"));
    I0.YearOptions.push(new I0.ItemViewModel("2019", "2019"));
    I0.YearOptions.push(new I0.ItemViewModel("2020", "2020"));
    I0.YearOptions.push(new I0.ItemViewModel("2021", "2021"));
    I0.YearOptions.push(new I0.ItemViewModel("2022", "2022"));
    I0.YearOptions.push(new I0.ItemViewModel("2023", "2023"));
    I0.YearOptions.push(new I0.ItemViewModel("2024", "2024"));
    I0.YearOptions.push(new I0.ItemViewModel("2025", "2025"));
    I0.ReviewStatus = new Array();
    I0.ReviewStatus.push(new I0.ItemViewModel("First Draft", "1"));
    I0.ReviewStatus.push(new I0.ItemViewModel("Work Document", "2"));
    I0.ReviewStatus.push(new I0.ItemViewModel("Pending Global Review", "3"));
    I0.ReviewStatus.push(new I0.ItemViewModel("Pending Final Review", "4"));
    I0.ReviewStatus.push(new I0.ItemViewModel("Finalized", "5"));
    I0.PriorityLevels = new Array();
    I0.PriorityLevels.push(new I0.ItemViewModel("Nice to Have", "1"));
    I0.PriorityLevels.push(new I0.ItemViewModel("Low", "2"));
    I0.PriorityLevels.push(new I0.ItemViewModel("Medium", "3"));
    I0.PriorityLevels.push(new I0.ItemViewModel("High", "4"));
    I0.PriorityLevels.push(new I0.ItemViewModel("Mandatory", "5"));
    I0.PrecisionScale = new Array();
    I0.PrecisionScale.push(new I0.ItemViewModel("Slightly Precise", "1"));
    I0.PrecisionScale.push(new I0.ItemViewModel("Moderately Precise", "2"));
    I0.PrecisionScale.push(new I0.ItemViewModel("Precise", "3"));
    I0.PrecisionScale.push(new I0.ItemViewModel("Very Precise", "4"));
    I0.PrecisionScale.push(new I0.ItemViewModel("Extremely Precise", "5"));
    I0.ScaleOptions = [new Array(), new Array(), new Array()];
    I0.ScaleOptions[0].push(new I0.ItemViewModel("Aggregate", "1"));
    I0.ScaleOptions[0].push(new I0.ItemViewModel("Subordinate", "2"));
    I0.ScaleOptions[1].push(new I0.ItemViewModel("UC User Goal", "1"));
    I0.ScaleOptions[1].push(new I0.ItemViewModel("UC Extension", "2"));
    I0.ScaleOptions[2].push(new I0.ItemViewModel("Application Level", "1"));
    I0.ScaleOptions[2].push(new I0.ItemViewModel("Screen Level", "2"));
    I0.StepOptions = new Array();
    I0.StepOptions.push(new I0.ItemViewModel("Step 1", "1"));
    I0.StepOptions.push(new I0.ItemViewModel("Step 2", "2"));
    I0.StepOptions.push(new I0.ItemViewModel("Step 3", "3"));
    I0.StepOptions.push(new I0.ItemViewModel("Step 4", "4"));
    I0.StepOptions.push(new I0.ItemViewModel("Step 5", "5"));
    I0.VersionStatusOptions = new Array();
    I0.VersionStatusOptions.push(new I0.ItemViewModel("Planned", "1"));
    I0.VersionStatusOptions.push(new I0.ItemViewModel("In Progress", "2"));
    I0.VersionStatusOptions.push(new I0.ItemViewModel("Completed", "3"));
    I0.VersionStatusOptions.push(new I0.ItemViewModel("Released", "4"));
    I0.CardinalityOptions = new Array();
    I0.CardinalityOptions.push(new I0.ItemViewModel("Has One", "1"));
    I0.CardinalityOptions.push(new I0.ItemViewModel("Has Many", "2"));
})(I0 || (I0 = {}));
