var I0;
(function (I0) {
    I0.sessionMockUp = new I0.UserSessionViewModel();
    I0.sessionMockUp.Role = new I0.UserRoleViewModel();
    I0.sessionMockUp.User = new I0.ItemViewModel("JohnDoe", "1");
    I0.sessionMockUp.Token = "hjgukhjoilj";
    I0.sessionMockUp.Projects = new Array();
    I0.sessionMockUp.Projects.push(new I0.ItemViewModel("Server MockUp Test", "44"));
    I0.sessionMockUp.Projects.push(new I0.ItemViewModel("Server Empty Test", "55"));
    I0.configExplorerMockUp = new I0.ExplorerViewModel(0);
    I0.configExplorerMockUp.MenuLists.push(new I0.ItemViewModelList());
    I0.configExplorerMockUp.MenuLists[0].Pool = new I0.ItemViewModel("Server", "0");
    I0.configExplorerMockUp.MenuLists[0].Items = new Array();
    I0.configExplorerMockUp.MenuLists[0].Items.push(new I0.ItemViewModel("MockUp Test", "1"));
    I0.configExplorerMockUp.MenuLists[0].Items.push(new I0.ItemViewModel("Empty Test", "0"));
    I0.projectMockUp = new I0.ProjectViewModel();
    I0.projectMockUp.Project = new I0.ItemViewModel("<<TEST MODE Project>>", "1");
    I0.projectMockUp.DashboardScreenVM = new I0.ScreenViewModel();
    I0.projectMockUp.DashboardScreenVM.Ressource = new I0.DefinitionViewModel("MockUp Test", 1);
    I0.projectMockUp.DashboardScreenVM.CardLists.push(new I0.DefinitionViewModelList());
    I0.projectMockUp.DashboardScreenVM.CardLists[0].Definitions.push(new I0.DefinitionViewModel("RULES", 0, 0, 0, 140, 90));
    I0.projectMockUp.DashboardScreenVM.CardLists[0].Definitions.push(new I0.DefinitionViewModel("FEATURES", 0, 0, 0, 65, 39));
    I0.projectMockUp.DashboardScreenVM.CardLists[0].Definitions.push(new I0.DefinitionViewModel("USE CASES", 0, 0, 0, 33, 14));
    I0.projectMockUp.DashboardScreenVM.CardLists[0].Definitions.push(new I0.DefinitionViewModel("PROFILES", 0, 0, 0, 10, 0));
    I0.projectMockUp.DashboardScreenVM.HistoryLogList.Items.push(new I0.ItemViewModel("Project Start", "2"));
    I0.projectMockUp.DashboardScreenVM.HistoryLogList.Items.push(new I0.ItemViewModel("Update", "3"));
    I0.projectMockUp.DashboardScreenVM.DownloadList.push(new I0.ItemViewModelList());
    I0.projectMockUp.DashboardScreenVM.DownloadList[0].Items = new Array();
    I0.projectMockUp.DashboardScreenVM.DownloadList[0].Items.push(new I0.ItemViewModel("Code Download", "1"));
    I0.projectMockUp.DashboardScreenVM.DownloadList[0].Items[0].Tooltip = "Code Download Lorem Ipsum";
    I0.projectMockUp.HistoryMarkerList.Items.push(new I0.ItemViewModel("V0.1 #BabyBoss", "2", 2019, 12));
    I0.projectMockUp.HistoryMarkerList.Items.push(new I0.ItemViewModel("V0.2 #MilkyWay", "3", 2020, 7));
    I0.projectMockUp.HistoryMarkerList.Items.push(new I0.ItemViewModel("V0.3 #Blue", "4", 2020, 12));
    I0.projectMockUp.HistoryMarkerList.Items.push(new I0.ItemViewModel("V0.4 #ReadyRed", "5", 2021, 6));
    I0.projectMockUp.HistoryMarkerList.Items.push(new I0.ItemViewModel("V0.5 #Lux", "6", 2022, 1));
    I0.projectMockUp.ScopeProfiles = new Array();
    I0.projectMockUp.ScopeProfiles.push(new I0.ItemViewModel("Demo", "1", 54, 25));
    I0.projectMockUp.ScopeProfiles.push(new I0.ItemViewModel("Client 1", "2", 48, 18));
    I0.projectMockUp.ScopeProfiles.push(new I0.ItemViewModel("Client 2", "4", 44, 13));
    I0.projectMockUp.ScopeProfiles.push(new I0.ItemViewModel("Prospect 1", "5", 39, 11));
    I0.projectMockUp.ScopeProfiles.push(new I0.ItemViewModel("Prospect 2", "7", 36, 4));
    I0.projectMockUp.RequirementExplorerVM = new I0.ExplorerViewModel(1);
    I0.projectMockUp.RequirementExplorerVM.MenuLists.push(new I0.ItemViewModelList());
    I0.projectMockUp.RequirementExplorerVM.MenuLists[0].Pool = new I0.ItemViewModel("Infrastructure", "1");
    I0.projectMockUp.RequirementExplorerVM.MenuLists[0].Items = new Array();
    I0.projectMockUp.RequirementExplorerVM.MenuLists[0].Items.push(new I0.ItemViewModel("Log Into Application", "1"));
    I0.projectMockUp.RequirementExplorerVM.MenuLists[0].Items.push(new I0.ItemViewModel("Reset Password", "10"));
    I0.projectMockUp.DomainExplorerVM = new I0.ExplorerViewModel(2);
    I0.projectMockUp.DomainExplorerVM.MenuLists.push(new I0.ItemViewModelList());
    I0.projectMockUp.DomainExplorerVM.MenuLists[0].Pool = new I0.ItemViewModel("Finance", "2");
    I0.projectMockUp.DomainExplorerVM.MenuLists[0].Items = new Array();
    I0.projectMockUp.DomainExplorerVM.MenuLists[0].Items.push(new I0.ItemViewModel("Concept 1", "2"));
    I0.projectMockUp.DomainExplorerVM.MenuLists[0].Items.push(new I0.ItemViewModel("Concept 2", "20"));
    I0.projectMockUp.RoadMapExplorerVM = new I0.ExplorerViewModel(3);
    I0.projectMockUp.RoadMapExplorerVM.MenuLists.push(new I0.ItemViewModelList());
    I0.projectMockUp.RoadMapExplorerVM.MenuLists[0].Pool = new I0.ItemViewModel("Product X", "3");
    I0.projectMockUp.RoadMapExplorerVM.MenuLists[0].Items = new Array();
    I0.projectMockUp.RoadMapExplorerVM.MenuLists[0].Items.push(new I0.ItemViewModel("Version 1", "3"));
    I0.projectMockUp.RoadMapExplorerVM.MenuLists[0].Items.push(new I0.ItemViewModel("Version 2", "30"));
    I0.UCScreenMockUp = new I0.ScreenViewModel();
    I0.UCScreenMockUp.Ressource = new I0.DefinitionViewModel("Log Into Application", 0);
    I0.UCScreenMockUp.CardLists.push(new I0.DefinitionViewModelList());
    I0.UCScreenMockUp.CardOptionLists.push(new I0.ItemViewModelList());
    I0.UCScreenMockUp.CardOptionLists[0].Items = new Array();
    I0.UCScreenMockUp.CardOptionLists[0].Items.push(new I0.ItemViewModel("Concept Char.", "44"));
    I0.UCScreenMockUp.CardOptionLists[0].Items.push(new I0.ItemViewModel("Concept Char.", "55"));
    I0.UCScreenMockUp.CardOptionLists[0].Items.push(new I0.ItemViewModel("Concept Char.", "66"));
    I0.conceptScreenMockUp = new I0.ScreenViewModel();
    I0.roadmapScreenMockUp = new I0.ScreenViewModel();
    I0.matrixScreenMockUp = new I0.ScreenViewModel();
})(I0 || (I0 = {}));
